[toolchain]


[features]
resolution = true
skip-lint = false

[programs.localnet]
wall_streets = "52RpWzznoBMHkRJsHNyXXsU5AxqZxYXn9KcyyL8jNJsA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
